import React from 'react';
import Head from 'next/head';
import { makeStyles } from '@material-ui/core/styles';
import Paper from '@material-ui/core/Paper';
import Grid from '@material-ui/core/Grid';

const useStyles = makeStyles((theme) => ({
	root: {
		flexGrow: 1,
	},
	paper: {
		padding: theme.spacing(1),
		textAlign: 'center',
		color: theme.palette.text.secondary,
	},
}));

export default function Home({ videoId }) {
	const classes = useStyles();

	function FormRow() {
		return (
			<React.Fragment>
				<Grid item xs={4}>
					<Paper className={classes.paper}>
						{' '}
						<iframe
							src="https://www.youtube.com/embed/${videoId}"
							title="YouTube video player"
							frameBorder="1"
							allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
							allowFullScreen
						></iframe>
					</Paper>
				</Grid>
				<Grid item xs={4}>
					<Paper className={classes.paper}>
						{' '}
						<iframe
							src="https://www.youtube.com/embed/AETFvQonfV8"
							title="YouTube video player"
							frameBorder="1"
							allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
							allowFullScreen
						></iframe>
					</Paper>
				</Grid>
				<Grid item xs={4}>
					<Paper className={classes.paper}>
						{' '}
						<iframe
							src="https://www.youtube.com/embed/AETFvQonfV8"
							title="YouTube video player"
							frameBorder="1"
							allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
							allowFullScreen
						></iframe>
					</Paper>
				</Grid>
			</React.Fragment>
		);
	}

	return (
		<>
			<Head>
				<title>Youtube App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={classes.root}>
				<Grid container spacing={1}>
					<Grid container item xs={12} spacing={3}>
						<FormRow />
					</Grid>
					<Grid container item xs={12} spacing={3}>
						<FormRow />
					</Grid>
					<Grid container item xs={12} spacing={3}>
						<FormRow />
					</Grid>
				</Grid>
			</div>
		</>
	);
}

export const getStaticProps = async (context) => {
	const resp = await fetch(
		'https://www.googleapis.com/youtube/v3/search?part=snippet&q=Neeraj Chopra &key=AIzaSyB__XcjvWZY8JKXQR6xFMvOM0A5EyB8RoI&order=date&maxResults=10'
	);

	const data = await resp.json();

	console.log('resp => ', data.items[0].id.videoId);

	return {
		props: { videoId: data.items[0].id.videoId },
	};
};
